### ISSUE TITLE
dprint on mac using asdf-dprint 

### ISSUE THREAD

**Issue by vincentbriglia** [asdf-community/asdf-dprint#3]
### Provide environment information

```bash
asdf info
OS:
Darwin MacBook-Pro-111.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

SHELL:
zsh 5.9 (x86_64-apple-darwin22.0)

BASH VERSION:
3.2.57(1)-release

ASDF VERSION:
v0.12.0
```

### To Reproduce

```
$ asdf install dprint 0.41.0 
\e[31mFail:\e[m Unsupported architecture
```
using 
```
$ uname -m               
arm64
```

### Describe the Bug

the two targets for Mac for dprint 0.41.0 are: 

  target: "x86_64-apple-darwin",
  target: "aarch64-apple-darwin",

### Expected Behaviour

I'd expect the asdf plugin to install the right version for my architecture, following this thread: https://github.com/dprint/dprint/issues/434 it seems that for arm64, the correct version is `aarch64`

**Comment by nicoandmee** [comment]
+1 for this also
